config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, :controllers => { :registrations => "users/registrations"}
  root 'welcome#index'
  get 'ads/index'

  resources :introductions

  resources :notices

  resources :messages do
    member do
      post :join
      post :quit
    end
  end

  resources :offers do
    member do
      post :join
      post :quit
    end
  end

  resources :games
  resources :industries
  resources :educations
  resources :lists
  resources :works
  resources :exchanges do
    resources :comments
  end

  namespace :admin do
    resources :introductions
    resources :notices
    resources :messages do
      member do
        post :publish
        post :hide
      end
    end
    resources :offers do
      member do
        post :publish
        post :hide
      end
    end
    resources :games
    resources :industries
    resources :educations
    resources :lists
    resources :works
    resources :exchanges do
      member do
        post :publish
        post :hide
      end
    end
    resources :users
  end

  namespace :account do
    resources :users
    resources :message_collections
    resources :offer_collections
    resources :exchange_collections
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :exchange
  validates :content, presence: true
end

app/models/education.rb
class Education < ApplicationRecord
  mount_uploader :image, ImageUploader
  is_impressionable

  belongs_to :user
  validates :title, presence: true
end

app/models/exchange.rb
class Exchange < ApplicationRecord
  mount_uploader :image, ImageUploader
  is_impressionable

  belongs_to :user
  validates :title, presence: true

  has_many :comments

  has_many :exchange_collections
  has_many :members, through: :exchange_collections, source: :user

  def publish!
    self.is_hidden = false
    self.save
  end

  def hide!
    self.is_hidden = true
    self.save
  end
end

app/models/game.rb
class Game < ApplicationRecord
  mount_uploader :image, ImageUploader
  is_impressionable

  belongs_to :user
  validates :title, presence: true
end

app/models/industry.rb
class Industry < ApplicationRecord
  mount_uploader :image, ImageUploader
  is_impressionable

  belongs_to :user
  validates :title, presence: true
end

app/models/introduction.rb
class Introduction < ApplicationRecord
  mount_uploader :image, ImageUploader
  is_impressionable
end

app/models/list.rb
class List < ApplicationRecord
  mount_uploader :image, ImageUploader
  is_impressionable

  belongs_to :user
  validates :title, presence: true
end

app/models/message.rb
class Message < ApplicationRecord
  mount_uploader :image, ImageUploader
  is_impressionable

  belongs_to :user
  validates :title, presence: true

  has_many :message_collections
  has_many :members, through: :message_collections, source: :user

  def publish!
  self.is_hidden = false
  self.save
  end

  def hide!
  self.is_hidden = true
  self.save
  end
end

app/models/notice.rb
class Notice < ApplicationRecord
  mount_uploader :image, ImageUploader
  is_impressionable

  belongs_to :user
  validates :title, presence: true
end

app/models/offer.rb
class Offer < ApplicationRecord
  mount_uploader :image, ImageUploader
  is_impressionable

  belongs_to :user
  validates :title, presence: true

  has_many :offer_collections
  has_many :members, through: :offer_collections, source: :user

  def publish!
  self.is_hidden = false
  self.save
  end

  def hide!
  self.is_hidden = true
  self.save
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def admin?
    is_admin
  end

  has_many :introductions

  has_many :games

  has_many :messages

  has_many :message_collections
  has_many :participated_messages, through: :message_collections, source: :message

  def is_member_of?(message)
    participated_messages.include?(message)
  end

  def join_message_collection!(message)
    participated_messages << message
  end

  def quit_message_collection!(message)
    participated_messages.delete(message)
  end

  has_many :offers

  has_many :offer_collections
  has_many :participated_offers, through: :offer_collections, source: :offer

  def is_member_of?(offer)
    participated_offers.include?(offer)
  end

  def join_offer_collection!(offer)
    participated_offers << offer
  end

  def quit_offer_collection!(offer)
    participated_offers.delete(offer)
  end

  has_many :notices

  has_many :educations

  has_many :exchanges
  has_many :exchange_collections
  has_many :participated_exchanges, through: :exchange_collections, source: :exchange

  def is_member_of?(exchange)
    participated_exchanges.include?(exchange)
  end

  def join_exchange_collection!(exchange)
    participated_exchanges << exchange
  end

  def quit_exchange_collection!(exchange)
    participated_exchanges.delete(exchange)
  end

  has_many :industries

  has_many :lists

  has_many :works

  has_many :comments

  validates_uniqueness_of :name

  mount_uploader :avatar, ImageUploader


end

app/models/welcome.rb
class Welcome < ApplicationRecord
  is_impressionable
end

app/models/work.rb
class Work < ApplicationRecord
  mount_uploader :image, ImageUploader
  is_impressionable

  belongs_to :user
  validates :title, presence: true
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @introductions = Introduction.order("updated_at DESC").page(params[:page]).per(5)                     #了解促进会
    @notices = Notice.order("updated_at DESC").page(params[:page]).per(9)                                 #广告
    @messages = Message.where(:is_hidden => false).order("updated_at DESC").page(params[:page]).per(5)    #本会动态
    @offers = Offer.where(:is_hidden => false).order("updated_at DESC").page(params[:page]).per(5)        #人才伯乐
    @exchanges = Exchange.order("updated_at DESC").page(params[:page]).per(5)                             #作品交流
    @educations = Education.order("updated_at DESC").page(params[:page]).per(5)                           #各地皮雕培训
    @lists = List.order("updated_at DESC").page(params[:page]).per(5)                                     #获奖作品
    @industries = Industry.order("updated_at DESC").page(params[:page]).per(5)                            #行业资讯
    @works = Work.order("updated_at DESC").page(params[:page]).per(5)                                     #参赛作品
    @games = Game.order("updated_at DESC").page(params[:page]).per(1)                                     #皮雕大赛
  end

end

app/helpers/ads_helper.rb
module AdsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice", "warning"
  end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/notices_helper.rb
module NoticesHelper
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/welcome/index.html.erb
<!--飘窗广告区域-->

<style type="text/css">
  #img {
  position: absolute;
  background: url(http://yixiu2017.oss-cn-shenzhen.aliyuncs.com/firsttest2.jpeg) no-repeat;
  width: 200px;
  height: 200px;
  }
  #img a {
  text-decoration: none;
  color: green;
  display: block;
  text-align: center;
  line-height: 20px;
  padding: 95px 5px;
  }
  #img .reset {
  position: absolute;
  top: -17px;
  right: 1px;
  font-size: 12px;
  }
</style>

<div id="img" style="z-index: 100; position: absolute; cursor: pointer; left: 894px; top: 458px;">
 <a href="http://www.szleathercraft.com/messages/15" target="_blank"></a>
 <div class="reset">关闭×</div>
</div>

<script language="javascript" type="text/javascript">
/*
*   jQuery Plugins imgFloat v1011
* 使用说明：
*   speed //元素移动速度
*   xPos  //元素一开始左距离
*   yPos  //元素一开始上距离
*   $('#div1').imgFloat({speed:30,xPos:10,yPos:10});
*   $('#div2').imgFloat();   //不给参数默认（speed:15,xPos:0,yPos:0）
*/
(function($) {
 jQuery.fn.imgFloat = function(options) {
   var own = this;
   var xD = 0;
   var yD = 0;
   var i = 1;
   var settings = {
     speed : 15,
     xPos : 0,
     yPos : 0
   };
   jQuery.extend(settings, options);
   var ownTop = settings.xPos;
   var ownLeft = settings.yPos;
   own.css({
     position : "absolute",
     cursor : "pointer"
   });
   function imgPosition() {
     var winWidth = $(window).width() - own.width();
     var winHeight = $(window).height() - own.height();
     if (xD == 0) {
       ownLeft += i;
       own.css({
         left : ownLeft
       });
       if (ownLeft >= winWidth) {
         ownLeft = winWidth;
         xD = 1;
       }
     }
     if (xD == 1) {
       ownLeft -= i;
       own.css({
         left : ownLeft
       });
       if (ownLeft <= 0)
         xD = 0;
     }
     if (yD == 0) {
       ownTop += i;
       own.css({
         top : ownTop
       });
       if (ownTop >= winHeight) {
         ownTop = winHeight;
         yD = 1;
       }
     }
     if (yD == 1) {
       ownTop -= i;
       own.css({
         top : ownTop
       });
       if (ownTop <= 0)
         yD = 0;
     }
   }
   var imgHover = setInterval(imgPosition, settings.speed);
   own.hover(function() {
     clearInterval(imgHover);
   }, function() {
     imgHover = setInterval(imgPosition, settings.speed);
   });
 }
})(jQuery);
</script>
<script language="javascript" type="text/javascript">
 //$("#img").imgFloat();   //不给参数默认（speed:10,xPos:0,yPos:0）
 $("#img").imgFloat({
   speed : 15,
   xPos : 10,
   yPos : 10
 });
 $(".reset").click(function() {
   $("#img").css("display", "none");
 });
</script>


<!-- 滚动图区域 -->
<!-- <div class="row">
  <div class="carousel fade-carousel slide" data-ride="carousel" data-interval="4000" id="bs-carousel">
    <div class="overlay"></div> -->

    <!-- 默认三张图列表 -->
    <!-- <div class="banner">
      <ul class="carousel-indicators "> -->
        <!-- <li data-target="#bs-carousel" data-slide-to="0" class="active"></li>
         <li data-target="#bs-carousel" data-slide-to="1"></li>
        <li data-target="#bs-carousel" data-slide-to="2"></li> -->
      <!-- </ul>
    </div> -->

    <!-- 文案部分 -->
    <!-- <div class="carousel-inner">
      <div class="item slides active">
        <div class="slide-1 img-responsive"></div>
        <div class="hero row"> -->
          <!-- <hgroup>
              <h1>这里</h1>
              <h3>活动异彩纷呈！</h3>
          </hgroup> -->
        <!-- </div>
      </div> -->
      <!-- <div class="item slides">
        <div class="slide-2"></div>
        <div class="hero">
          <hgroup>
              <h1>这里</h1>
              <h3>皮雕爱好者温暖的港湾！</h3>
          </hgroup>
        </div>
      </div>
      <div class="item slides">
        <div class="slide-3"></div>
        <div class="hero">
          <hgroup>
              <h1>这里</h1>
              <h3>大师云集，与你同行！</h3>
          </hgroup>
        </div>
      </div> -->
<!--
    </div>
  </div>
</div> -->

<div class= "container">
  <div class="row">
  <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <!-- <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li> -->
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner block-center">
      <div class="item active ">
        <img src="http://yixiu2017.oss-cn-shenzhen.aliyuncs.com/first-index3.gif" alt="Los Angeles">
      </div>
<!--
      <div class="item">
        <img src="http://yixiu2017.oss-cn-shenzhen.aliyuncs.com/first-index3.gif" alt="Chicago">
      </div>

      <div class="item">
        <img src="http://yixiu2017.oss-cn-shenzhen.aliyuncs.com/first-index3.gif" alt="New York">
      </div> -->
    </div>
  </div>
</div>
</div>

<!--
<div class="container">
  <div class="row">
    <div class="col-md-12  ">
      <img src="http://yixiu2017.oss-cn-shenzhen.aliyuncs.com/first-index3.gif" class= "img-responsive top-image" width= "1200px" >
    </div>
  </div>
</div> -->


<!-- 皮雕比赛区域 -->
<!-- <hr> -->
<br>
<div class="container">
  <!-- <div class="row nav-container">
    <div class="col-xs-12 text-center">
      <h5>皮雕大赛精彩回顾</h5>
    </div>
  </div> -->

  <div class="row index-content">
    <% @games.each do |game| %>
        <div class="col-xs-12>
          <%= link_to game_path(game) do %>
            <% if game.image.url.present? %>
              <%= link_to image_tag(game.image.large.url, class: "img-responsive center-block  game-image"), game_path(game) %>
            <% else %>
              <%= link_to image_tag("http://placehold.it/1200x200&text=No Pic", class: "img-responsive center-block"), game_path(game) %>
            <% end %>
          <% end %>
        </div>
    <% end %>
  </div>
</div>


<div class="container">
  <div class="row topspan">
    <!-- 了解促进会区域 -->
    <div class="col-lg-3 col-md-6 col-xs-6">
      <h4 class="text-center">了解促进会</h4>
      <table class="table table-striped">
        <% @introductions.each do |introduction| %>
          <div class="col-md-12">
            <tr>
              <td>
                <div style="overflow:hidden; text-overflow:ellipsis; white-space:nowrap; width:200px;">
                  <%= link_to(introduction.title, introduction_path(introduction)) %>
                </div>
              </td>
            </tr>
          </div>
        <% end %>
      </table>
      <div class="col-md-12">
        <%= link_to("更多 >>", introductions_path, class: "pull-left") %>
      </div>
    </div>

    <!-- 本会动态区域 -->
    <div class="col-lg-3 col-md-6 col-xs-6 index-border" >
      <h4 class="text-center">本会动态</h4>
      <table class="table table-striped">
        <% @messages.each do |message| %>
            <div class="col-md-12">
              <tr>
                <td>
                  <div style="overflow:hidden; text-overflow:ellipsis; white-space:nowrap; width:200px;">
                    <%= link_to(message.title, message_path(message)) %>
                  </div>
                </td>
              </tr>
            </div>
        <% end %>
      </table>
      <div class="col-md-12">
        <%= link_to("更多 >>", messages_path, class: "pull-left") %>
      </div>
    </div>

    <!-- 行业资讯区域 -->
    <div class="col-lg-3 col-md-6 col-xs-6" >
      <h4 class="text-center">行业资讯</h4>
      <table class="table table-striped">
        <% @industries.each do |industry| %>
            <div class="col-md-12">
              <tr>
                <td>
                  <div style="overflow:hidden; text-overflow:ellipsis; white-space:nowrap; width:200px;">
                    <%= link_to(industry.title, industry_path(industry)) %>
                  </div>
                </td>
              </tr>
            </div>
        <% end %>
      </table>
      <div class="col-md-12">
        <%= link_to("更多 >>", industries_path, class: "pull-left") %>
      </div>
    </div>

    <!-- 国内外作品交流区域 -->
    <div class="col-lg-3 col-md-6 col-xs-6" >
      <h4 class="text-center">国内外作品交流</h4>
      <table class="table table-striped">
        <% @exchanges.each do |exchange| %>
            <div class="col-md-12">
              <tr>
                <td>
                  <div style="overflow:hidden; text-overflow:ellipsis; white-space:nowrap; width:200px;">
                    <%= link_to(exchange.title, exchange_path(exchange)) %>
                  </div>
                </td>
              </tr>
            </div>
        <% end %>
      </table>
      <div class="col-md-12">
        <%= link_to("更多 >>", exchanges_path, class: "pull-left") %>
      </div>
    </div>
  </div>
</div>

<!-- 人才伯乐\比赛作品\培训区域 -->
<hr>
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <div class="col-lg-3 col-md-6 col-xs-6">
        <h4 class="text-center">
          <%= link_to("人才•伯乐", offers_path) %>
        </h4>
      </div>
      <div class="col-lg-3 col-md-6 col-xs-6">
        <h4 class="text-center">
          <%= link_to("皮雕艺术大赛部分作品欣赏", works_path) %>
        </h4>
      </div>
      <div class="col-lg-3 col-md-6 col-xs-6">
        <h4 class="text-center">
          <%= link_to("皮雕艺术大赛获奖作品名单", lists_path) %>
        </h4>
      </div>
      <div class="col-lg-3 col-md-6 col-xs-6">
        <h4 class="text-center">
          <%= link_to("各地皮雕培训、体验", educations_path) %>
        </h4>
      </div>
    </div>
  </div>
</div>

<!-- 各地培训信息区域 -->
<!-- <hr>
<div class="row">
  <div class="col-md-12 text-center">
    <%= link_to("各地皮雕培训、体验", educations_path, class: "btn btn-md btn-info", target: "_blank") %>
  </div>
</div> -->

<!-- 优秀会员单位展示 -->
<hr>
<div class="container">
  <div class="row index-content">
    <div class="col-md-12">
      <h5>促进会部分优秀会员单位</h5>
      <% @notices.each do |notice| %>
        <div class="col-lg-3 col-md-3 col-xs-3">
            <%= link_to notice_path(notice) do %>
              <% if notice.image.url.present? %>
                <%= link_to image_tag(notice.image.ad.url, class: "img-responsive center-block  adv-image"), notice_path(notice) %>
              <% else %>
                <%= link_to image_tag("http://placehold.it/120x50&text=No Pic", class: "img-responsive center-block adv-image"), notice_path(notice) %>
              <% end %>
            <% end %>
            <div class="text-center">
              <%= link_to(notice.title, notice_path(notice), class: "text") %>
            </div>
        </div>

      <% end %>

    </div>
  </div>
</div>
<br><br><br>


<!-- 广告招商区域 -->

<div class="row">
  <div class="col-md-12 text-center">
    <%= link_to("本广告位招商", ads_index_path, class: "btn btn-md btn-warning", target: "_blank") %>
  </div>
</div>

<!-- 协会链接区域 -->
<hr>
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="text-center">
        <h4>相关协会</h4>
      </div>
      <div class="col-md-4 col-xs-4 text-right">
        <%= link_to("深圳市工艺美术行业协会", "http://www.artcraft.com.cn/",  target: "_blank") %>
      </div>
      <div class="col-md-4 col-xs-4 text-center">
        <%= link_to("深圳市皮革行业协会", "http://www.szleather.com/",  target: "_blank") %>
      </div>
      <div class="col-md-4 col-xs-4 text-left">
        <%= link_to("中国工艺美术协会", "http://www.cnaca.org/",  target: "_blank") %>
      </div>
      <div class="col-md-6 col-xs-4 text-right">
        <%= link_to("日本革工艺会", "http://japan-leather.com/",  target: "_blank") %>
      </div>
      <div class="col-md-6 col-xs-4 text-left">
        美国皮雕联合会
      </div>
    </div>
  </div>
</div>