config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, :controllers => { :registrations => "users/registrations"}
  root 'welcome#index'
  get 'ads/index'

  resources :introductions

  resources :notices

  resources :messages do
    member do
      post :join
      post :quit
    end
  end

  resources :offers do
    member do
      post :join
      post :quit
    end
  end

  resources :games
  resources :industries
  resources :educations
  resources :lists
  resources :works
  resources :exchanges do
    resources :comments
  end

  namespace :admin do
    resources :introductions
    resources :notices
    resources :messages do
      member do
        post :publish
        post :hide
      end
    end
    resources :offers do
      member do
        post :publish
        post :hide
      end
    end
    resources :games
    resources :industries
    resources :educations
    resources :lists
    resources :works
    resources :exchanges do
      member do
        post :publish
        post :hide
      end
    end
    resources :users
  end

  namespace :account do
    resources :users
    resources :message_collections
    resources :offer_collections
    resources :exchange_collections
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :exchange
  validates :content, presence: true
end

app/models/education.rb
class Education < ApplicationRecord
  mount_uploader :image, ImageUploader
  is_impressionable

  belongs_to :user
  validates :title, presence: true
end

app/models/exchange.rb
class Exchange < ApplicationRecord
  mount_uploader :image, ImageUploader
  is_impressionable

  belongs_to :user
  validates :title, presence: true

  has_many :comments

  has_many :exchange_collections
  has_many :members, through: :exchange_collections, source: :user

  def publish!
    self.is_hidden = false
    self.save
  end

  def hide!
    self.is_hidden = true
    self.save
  end
end

app/models/game.rb
class Game < ApplicationRecord
  mount_uploader :image, ImageUploader
  is_impressionable

  belongs_to :user
  validates :title, presence: true
end

app/models/industry.rb
class Industry < ApplicationRecord
  mount_uploader :image, ImageUploader
  is_impressionable

  belongs_to :user
  validates :title, presence: true
end

app/models/introduction.rb
class Introduction < ApplicationRecord
  mount_uploader :image, ImageUploader
  is_impressionable
end

app/models/list.rb
class List < ApplicationRecord
  mount_uploader :image, ImageUploader
  is_impressionable

  belongs_to :user
  validates :title, presence: true
end

app/models/message.rb
class Message < ApplicationRecord
  mount_uploader :image, ImageUploader
  is_impressionable

  belongs_to :user
  validates :title, presence: true

  has_many :message_collections
  has_many :members, through: :message_collections, source: :user

  def publish!
  self.is_hidden = false
  self.save
  end

  def hide!
  self.is_hidden = true
  self.save
  end
end

app/models/notice.rb
class Notice < ApplicationRecord
  mount_uploader :image, ImageUploader
  is_impressionable

  belongs_to :user
  validates :title, presence: true
end

app/models/offer.rb
class Offer < ApplicationRecord
  mount_uploader :image, ImageUploader
  is_impressionable

  belongs_to :user
  validates :title, presence: true

  has_many :offer_collections
  has_many :members, through: :offer_collections, source: :user

  def publish!
  self.is_hidden = false
  self.save
  end

  def hide!
  self.is_hidden = true
  self.save
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def admin?
    is_admin
  end

  has_many :introductions

  has_many :games

  has_many :messages

  has_many :message_collections
  has_many :participated_messages, through: :message_collections, source: :message

  def is_member_of?(message)
    participated_messages.include?(message)
  end

  def join_message_collection!(message)
    participated_messages << message
  end

  def quit_message_collection!(message)
    participated_messages.delete(message)
  end

  has_many :offers

  has_many :offer_collections
  has_many :participated_offers, through: :offer_collections, source: :offer

  def is_member_of?(offer)
    participated_offers.include?(offer)
  end

  def join_offer_collection!(offer)
    participated_offers << offer
  end

  def quit_offer_collection!(offer)
    participated_offers.delete(offer)
  end

  has_many :notices

  has_many :educations

  has_many :exchanges
  has_many :exchange_collections
  has_many :participated_exchanges, through: :exchange_collections, source: :exchange

  def is_member_of?(exchange)
    participated_exchanges.include?(exchange)
  end

  def join_exchange_collection!(exchange)
    participated_exchanges << exchange
  end

  def quit_exchange_collection!(exchange)
    participated_exchanges.delete(exchange)
  end

  has_many :industries

  has_many :lists

  has_many :works

  has_many :comments

  validates_uniqueness_of :name

  mount_uploader :avatar, ImageUploader


end

app/models/welcome.rb
class Welcome < ApplicationRecord
  is_impressionable
end

app/models/work.rb
class Work < ApplicationRecord
  mount_uploader :image, ImageUploader
  is_impressionable

  belongs_to :user
  validates :title, presence: true
end

app/controllers/admin/works_controller.rb
class Admin::WorksController < ApplicationController
  layout "admin"
  before_action :authenticate_user!, only: [:new, :create, :update, :edit, :destroy]
  before_action :require_is_admin

  def index
    @works = Work.order("created_at DESC").page(params[:page]).per(20)
  end

  def new
    @work = Work.new
  end

  def show
    @work = Work.find(params[:id])
  end

  def edit
    @work = Work.find(params[:id])
  end

  def create
    @work = Work.new(work_params)
    @work.user = current_user
    if @work.save
      redirect_to admin_works_path
    else
      render :new
    end
  end

  def update
    @work = Work.find(params[:id])
    if @work.update(work_params)
      redirect_to admin_works_path
    else
      render :edit
    end
  end

  def destroy
    @work = Work.find(params[:id])
    @work.destroy
    redirect_to admin_works_path
  end

  private

  def work_params
    params.require(:work).permit(:title, :description, :image)
  end
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  impressionist

  def index
    @works = Work.order("created_at DESC").page(params[:page]).per(20)
  end

  def show
    @work = Work.find(params[:id])
    impressionist(@work)
  end
end

app/helpers/admin/works_helper.rb
module Admin::WorksHelper
end

app/helpers/ads_helper.rb
module AdsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice", "warning"
  end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/notices_helper.rb
module NoticesHelper
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/admin/works/_form.html.erb
<%= simple_form_for [:admin, @work] do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title, :label => "标题" %>
    <% if @work.image.url.present? %>
     <span>目前封面图</span><br>
     <%= image_tag(@work.image.small.url) %>
    <% end %>
    <%= f.input :image,  as: :file, :label => "封面" %>
    <div style="display: none;">
      <%= f.input :description, :label => "内容" %>
    </div>
    <div id="editor">
      <%== @work.description %>
    </div>
  </div>

  <%= f.submit "提交", class: "btn btn-sm btn-default", data: {disable_with: "Submiting..."} %>

<% end %>

<script>
  var E = window.wangEditor
  var editor = new E('#editor')
  editor.customConfig.uploadImgShowBase64 = true
  editor.customConfig.onchange = function (description) {
    $("#work_description").html(description)
  }
  editor.create()
</script>

app/views/admin/works/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10">
      <h2 class="text-center">编辑获奖作品</h2>
      <hr>
      <%= render "form" %>
    </div>
  </div>
</div>

app/views/admin/works/index.html.erb
<div class="container">
  <div class="row">
    <br><br><br>
    <div class="col-md-10">
      <h3 class="text-center">参赛作品欣赏</h3>
    </div>
    <br>
    <div class="col-md-10">
      <div>
        <%= link_to("增加参赛作品", new_admin_work_path, class: "btn btn-sm btn-default pull-right") %>
      </div>

      <table class="table table-hover table-bordered table-responsive">
        <thead>
          <tr>
            <td>标题</td>
            <td>发布时间</td>
            <td>操作</td>
          </tr>
        </thead>
        <tbody>
          <% @works.each do |work| %>
            <tr>
              <td><%= link_to(work.title, work_path(work))  %></td>

              <td><%= work.created_at %></td>
              <td>
                <%= link_to("编辑", edit_admin_work_path(work)) %> |
                <%= link_to("删除", admin_work_path(work), method: :delete, data: { confirm: "你确定要删除吗？"}) %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <div>
        <%= link_to("回到前台", root_path, class: "btn btn-sm btn-default pull-left") %>
      </div>
    </div>
  </div>
</div>

app/views/admin/works/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10">
      <h2 class="text-center">新增参赛作品</h2>
      <hr>
      <%= render "form" %>
    </div>
  </div>
</div>